"""
tests/backend/test_file_workflow_docx.py
-----------------------------------------
Regression tests for:
1. file_list returning actual workspace filenames (including names with spaces).
2. file_read accepting exact filenames returned by file_list (including spaces and .pdf/.docx formats).
3. Nonexistent / invented filenames must NOT be silently substituted.
4. Planner and execution engine dynamic canonical path resolution from file_list results.
5. Full 4-step workflow verification: file_list -> file_read -> docx_create -> artifact_verifier.
"""

from __future__ import annotations

import io
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from pypdf import PdfWriter

from backend.agent.engine import AgentEngine
from backend.agent.planner import AgentPlanner, PlanStep, StepStatus, PlanStatus
from backend.agent.task import TaskManager, TaskStatus
from backend.config import Settings
from backend.models.base import ChatResponse
from backend.tools.artifact_verifier import ArtifactVerifierInput, create_artifact_verifier
from backend.tools.docx_create import DocxCreateInput, create_docx_create
from backend.tools.file_list import FileListInput, create_file_list
from backend.tools.file_read import FileReadInput, create_file_read
from backend.tools.registry import ToolRegistry


def _create_minimal_pdf_bytes(title: str = "Pump Instability Analysis", content: str = "Vibration harmonic data.") -> bytes:
    """Create a valid in-memory PDF with text stream for testing."""
    writer = PdfWriter()
    page = writer.add_blank_page(width=612, height=792)
    buf = io.BytesIO()
    writer.write(buf)
    return buf.getvalue()


class TestFileListAndReadWorkflows:
    """Test file listing and direct reading of uploaded documents."""

    @pytest.mark.asyncio
    async def test_file_list_and_read_filename_containing_spaces(self, tmp_path: Path):
        """
        Test that files with spaces and doc prefixes on disk are:
        1. Cleanly listed by file_list without doc prefix.
        2. Successfully read by file_read using the exact clean filename with spaces.
        """
        # Create an uploaded file on disk with doc prefix and spaces
        disk_file = tmp_path / "doc_c966648ec632bcfd_Pump Instability Phenomena Generated by Fluid Forces.txt"
        disk_file.write_text("Detailed pump vibration and fluid forces observations.", encoding="utf-8")

        fl = create_file_list(tmp_path)
        files = await fl(FileListInput())
        assert len(files) == 1
        assert files[0]["filename"] == "Pump Instability Phenomena Generated by Fluid Forces.txt"
        assert files[0]["relative_path"] == "doc_c966648ec632bcfd_Pump Instability Phenomena Generated by Fluid Forces.txt"

        fr = create_file_read(tmp_path)
        # Read using exact clean filename with spaces
        result = await fr(FileReadInput(relative_path="Pump Instability Phenomena Generated by Fluid Forces.txt"))
        assert result["filename"] == "Pump Instability Phenomena Generated by Fluid Forces.txt"
        assert "Detailed pump vibration" in result["content"]

    @pytest.mark.asyncio
    async def test_nonexistent_invented_filename_not_silently_substituted(self, tmp_path: Path):
        """
        Test that when an invented or nonexistent filename is passed,
        file_read raises 'File not found' rather than silently substituting another file.
        """
        # Create one real file in the workspace
        (tmp_path / "doc_12345678_Pump Instability Phenomena Generated by Fluid Forces.txt").write_text(
            "Real content", encoding="utf-8"
        )

        fr = create_file_read(tmp_path)

        # 1. Invented filename that does not exist must fail clearly
        with pytest.raises(ValueError, match="File not found: 'Pump_Instability_Document.txt'"):
            await fr(FileReadInput(relative_path="Pump_Instability_Document.txt"))

        # 2. Another invented filename
        with pytest.raises(ValueError, match="File not found: 'pump_maintenance.pdf'"):
            await fr(FileReadInput(relative_path="pump_maintenance.pdf"))

        # 3. Completely arbitrary nonexistent filename
        with pytest.raises(ValueError, match="File not found: 'nonexistent.txt'"):
            await fr(FileReadInput(relative_path="nonexistent.txt"))

    @pytest.mark.asyncio
    async def test_canonical_path_resolution_using_file_list_results(self, tmp_path: Path):
        """
        Test that AgentEngine._resolve_canonical_file_path:
        1. Selects the actual filename from file_list results when given an invented placeholder.
        2. Preserves exact filenames containing spaces.
        3. Never substitutes unrelated nonexistent files.
        """
        engine = AgentEngine.__new__(AgentEngine)

        executed_step_results = [
            {
                "step_id": "step_1",
                "tool": "file_list",
                "success": True,
                "result": [
                    {
                        "filename": "Pump Instability Phenomena Generated by Fluid Forces.pdf",
                        "relative_path": "doc_c966648ec632bcfd_Pump Instability Phenomena Generated by Fluid Forces.pdf",
                        "extension": ".pdf",
                    },
                    {
                        "filename": "Occurrence of Sub-Synchronous Vibration in a Multistage Turbine Pump.pdf",
                        "relative_path": "doc_f7c92fa0aa8f5d8d_Occurrence of Sub-Synchronous Vibration in a Multistage Turbine Pump.pdf",
                        "extension": ".pdf",
                    },
                    {
                        "filename": "Petroleum Refining Effluent Guidelines Technical Support Document.pdf",
                        "relative_path": "doc_5481f0f246324b6a_Petroleum Refining Effluent Guidelines.pdf",
                        "extension": ".pdf",
                    },
                ],
            }
        ]

        # Case A: Invented placeholder path 'Pump_Instability_Document.txt' resolves to actual file
        resolved_a = engine._resolve_canonical_file_path(
            "Pump_Instability_Document.txt",
            executed_step_results,
            tmp_path,
            user_request="Create a DOCX report summarizing pump instability from uploaded files",
            step_description="Read the pump instability document from workspace",
        )
        assert resolved_a == "Pump Instability Phenomena Generated by Fluid Forces.pdf"

        # Case B: Exact filename with spaces is preserved
        resolved_b = engine._resolve_canonical_file_path(
            "Pump Instability Phenomena Generated by Fluid Forces.pdf",
            executed_step_results,
            tmp_path,
        )
        assert resolved_b == "Pump Instability Phenomena Generated by Fluid Forces.pdf"

        # Case C: Nonexistent file with no matching tokens in file_list is NOT substituted
        resolved_c = engine._resolve_canonical_file_path(
            "boiler_feedwater_failure_2024.txt",
            executed_step_results,
            tmp_path,
            user_request="Summarize boiler feedwater incident",
            step_description="Read boiler incident report",
        )
        assert resolved_c == "boiler_feedwater_failure_2024.txt"


class TestFullDocxGenerationWorkflow:
    """Test full 4-step workflow: file_list -> file_read -> docx_create -> artifact_verifier."""

    @pytest.mark.asyncio
    async def test_successful_docx_generation_from_uploaded_document(self, tmp_path: Path):
        """
        Verify the complete 4-step workflow:
        1. file_list returns the available uploaded document.
        2. file_read reads the document content using the exact filename.
        3. docx_create creates a genuine Word document with the extracted content.
        4. artifact_verifier verifies the created Word document on disk.
        """
        upload_dir = tmp_path / "uploads"
        sandbox_dir = tmp_path / "sandbox"
        upload_dir.mkdir(parents=True, exist_ok=True)
        sandbox_dir.mkdir(parents=True, exist_ok=True)

        # Create an uploaded PDF document
        pdf_bytes = _create_minimal_pdf_bytes()
        disk_pdf = upload_dir / "doc_c966648ec632bcfd_Pump Instability Phenomena Generated by Fluid Forces.pdf"
        disk_pdf.write_bytes(pdf_bytes)

        # Mock DocumentParser._parse_pdf so it returns rich extracted text without external binary dependencies
        extracted_text = (
            "PUMP INSTABILITY PHENOMENA GENERATED BY FLUID FORCES\n"
            "Summary of multi-stage pump vibration observations and rotor dynamics.\n"
            "Sub-synchronous fluid excitation detected in diffuser passages."
        )

        with patch("backend.rag.ingest.DocumentParser._parse_pdf", return_value=(extracted_text, {"page_count": 1})):
            # Step 1: file_list
            fl_tool = create_file_list(upload_dir)
            files = await fl_tool(FileListInput())
            assert len(files) == 1
            exact_filename = files[0]["filename"]
            assert exact_filename == "Pump Instability Phenomena Generated by Fluid Forces.pdf"

            # Step 2: file_read using exact returned filename with spaces
            fr_tool = create_file_read(upload_dir)
            read_result = await fr_tool(FileReadInput(relative_path=exact_filename))
            assert read_result["filename"] == exact_filename
            assert "PUMP INSTABILITY PHENOMENA" in read_result["content"]
            assert read_result["extension"] == ".pdf"

            # Step 3: docx_create
            docx_tool = create_docx_create(sandbox_dir)
            docx_result = await docx_tool(DocxCreateInput(
                filename="Pump_Instability_Report.docx",
                title="Pump Instability Technical Analysis",
                content=read_result["content"],
                overwrite=True,
            ))
            assert docx_result["filename"] == "Pump_Instability_Report.docx"
            assert docx_result["size_bytes"] > 0

            # Step 4: artifact_verifier
            verifier_tool = create_artifact_verifier(sandbox_dir)
            verify_result = await verifier_tool(ArtifactVerifierInput(
                relative_path="Pump_Instability_Report.docx",
                min_row_count=1,
                expected_content=["Pump", "Instability"],
            ))
            assert verify_result["verified"] is True
            assert verify_result["format"] == "docx"
            assert verify_result["sha256_hash"] is not None

    @pytest.mark.asyncio
    async def test_docx_create_renders_populated_table_rows_and_styled_headers(self, tmp_path: Path):
        """
        Verify that docx_create generates a genuine Word table with bold headers
        and populated data rows from args.tables.
        """
        docx_tool = create_docx_create(tmp_path)
        tables_input = [
            {
                "headers": ["Cause", "Source Document", "Supporting Finding"],
                "rows": [
                    [
                        "Fluid force excitation / Sub-synchronous whirl",
                        "Pump Instability Phenomena Generated by Fluid Forces.pdf",
                        "Interaction between rotor and fluid creates cross-coupled dynamic stiffness.",
                    ],
                    [
                        "Acoustic resonance in discharge piping",
                        "Pump Instability Phenomena Generated by Fluid Forces.pdf",
                        "Pressure pulsation frequencies amplify lateral vibration at natural frequencies.",
                    ],
                ],
            }
        ]

        result = await docx_tool(DocxCreateInput(
            filename="Pump_Instability_Report.docx",
            title="Pump Instability and Vibration Technical Report",
            content="Summary of main causes of pump instability and vibration.",
            tables=tables_input,
            overwrite=True,
        ))

        assert result["filename"] == "Pump_Instability_Report.docx"
        target_file = tmp_path / "Pump_Instability_Report.docx"
        assert target_file.exists()

        import docx
        doc = docx.Document(target_file)
        assert len(doc.tables) == 1
        tbl = doc.tables[0]
        # 1 header row + 2 data rows = 3 rows total
        assert len(tbl.rows) == 3

        # Verify header texts
        headers = [c.text.strip() for c in tbl.rows[0].cells]
        assert headers == ["Cause", "Source Document", "Supporting Finding"]

        # Verify header is bold
        assert any(r.bold for r in tbl.rows[0].cells[0].paragraphs[0].runs)

        # Verify data rows
        row1 = [c.text.strip() for c in tbl.rows[1].cells]
        assert "Fluid force excitation" in row1[0]
        assert row1[1] == "Pump Instability Phenomena Generated by Fluid Forces.pdf"
        assert "cross-coupled dynamic stiffness" in row1[2]

        row2 = [c.text.strip() for c in tbl.rows[2].cells]
        assert "Acoustic resonance" in row2[0]

    @pytest.mark.asyncio
    async def test_artifact_verifier_validates_docx_with_populated_tables(self, tmp_path: Path):
        """
        Verify that artifact_verifier successfully validates a DOCX document
        with expected columns and populated rows.
        """
        docx_tool = create_docx_create(tmp_path)
        await docx_tool(DocxCreateInput(
            filename="Pump_Instability_Report.docx",
            title="Pump Instability Report",
            content="A summary of pump vibration and instability.",
            tables=[
                {
                    "headers": ["Cause", "Source Document", "Supporting Finding"],
                    "rows": [
                        ["Fluid force excitation", "Pump_Instability.pdf", "Sub-synchronous whirl"],
                    ],
                }
            ],
            overwrite=True,
        ))

        verifier = create_artifact_verifier(tmp_path)
        verify_res = await verifier(ArtifactVerifierInput(
            relative_path="Pump_Instability_Report.docx",
            expected_columns=["Cause", "Source Document", "Supporting Finding"],
            expected_content=["Fluid force excitation", "whirl"],
            min_row_count=1,
        ))

        assert verify_res["verified"] is True
        assert verify_res["table_count"] == 1
        assert verify_res["table_data_row_count"] == 1
        assert "Cause" in verify_res["detected_headers"]
        assert "Source Document" in verify_res["detected_headers"]
        assert "Supporting Finding" in verify_res["detected_headers"]

    @pytest.mark.asyncio
    async def test_artifact_verifier_rejects_empty_table_in_docx(self, tmp_path: Path):
        """
        Verify that when a DOCX has table headers but 0 data rows,
        artifact_verifier raises a descriptive error explaining that the table has no data rows.
        """
        docx_tool = create_docx_create(tmp_path)
        await docx_tool(DocxCreateInput(
            filename="Empty_Table_Report.docx",
            title="Report With Empty Table",
            content="Short summary text.",
            tables=[
                {
                    "headers": ["Cause", "Source Document", "Supporting Finding"],
                    "rows": [],  # Empty rows!
                }
            ],
            overwrite=True,
        ))

        verifier = create_artifact_verifier(tmp_path)
        with pytest.raises(ValueError, match="no data rows \\(table is empty\\)"):
            await verifier(ArtifactVerifierInput(
                relative_path="Empty_Table_Report.docx",
                expected_columns=["Cause", "Source Document", "Supporting Finding"],
                min_row_count=1,
            ))

    @pytest.mark.asyncio
    async def test_artifact_verifier_handles_file_path_alias_and_nested_dict_expected_content(self, tmp_path: Path):
        """
        Verify that passing file_path (instead of relative_path) and a nested dict
        in expected_content (as produced by some planners) is handled gracefully without
        false-positive missing content errors for structural keys like 'tables'.
        """
        docx_tool = create_docx_create(tmp_path)
        await docx_tool(DocxCreateInput(
            filename="Pump_Instability_Report.docx",
            title="Pump Instability and Vibration Technical Report",
            content="Summary of main causes of pump instability and vibration.",
            tables=[
                {
                    "headers": ["Cause", "Source Document", "Supporting Finding"],
                    "rows": [
                        ["Fluid force excitation", "Pump_Instability.pdf", "Sub-synchronous whirl"],
                    ],
                }
            ],
            overwrite=True,
        ))

        verifier = create_artifact_verifier(tmp_path)
        # Pass file_path alias and nested dict expected_content
        verify_res = await verifier(ArtifactVerifierInput(
            file_path="Pump_Instability_Report.docx",
            expected_content={"tables": [{"headers": ["Cause", "Source Document", "Supporting Finding"], "rows": []}]},
            expected_columns=["Cause", "Source Document", "Supporting Finding"],
            min_row_count=1,
        ))
        assert verify_res["verified"] is True
        assert verify_res["status"] == "PASSED_VERIFICATION"

    @pytest.mark.asyncio
    async def test_planner_ensures_file_read_inserted_after_file_list(self):
        """
        Verify that when the user asks to create an artifact from uploaded files,
        AgentPlanner ensures file_read is inserted immediately after file_list,
        even if the LLM output skipped file_read.
        """
        planner = AgentPlanner(max_plan_steps=10)
        # Mock LLM returning plan with file_list but skipping file_read
        llm_response = [
            {"description": "List files in workspace", "tool_name": "file_list", "arguments": {}},
            {"description": "Summarize causes of pump instability", "tool_name": None, "arguments": {}},
            {"description": "Create report", "tool_name": "docx_create", "arguments": {"filename": "Pump_Report.docx"}},
            {"description": "Verify report", "tool_name": "artifact_verifier", "arguments": {"relative_path": "Pump_Report.docx"}},
        ]

        import json
        mock_provider = AsyncMock()
        mock_provider.chat.return_value = ChatResponse(
            content=json.dumps(llm_response),
            model="qwen2.5:7b",
            provider="ollama",
        )

        plan = await planner.create_plan(
            task_id="task_test_1",
            objective="Create a DOCX technical report using the uploaded PDF documents directly. Summarize pump instability.",
            tool_registry=None,
            provider=mock_provider,
            model_name="qwen2.5:7b",
        )

        step_tools = [s.tool_name for s in plan.steps]
        assert step_tools[0] == "file_list"
        assert step_tools[1] == "file_read"
        assert "docx_create" in step_tools
        assert "artifact_verifier" in step_tools

    @pytest.mark.asyncio
    async def test_engine_synthesizes_tabular_data_for_docx(self, tmp_path: Path):
        """
        Verify that AgentEngine._synthesize_tabular_data populates table headers and rows
        from executed file_read step results.
        """
        engine = AgentEngine.__new__(AgentEngine)
        engine._doc_service = None

        executed_step_results = [
            {
                "step_id": "step_1",
                "tool": "file_list",
                "success": True,
                "result": [
                    {"filename": "Pump Instability Phenomena Generated by Fluid Forces.pdf", "relative_path": "Pump Instability.pdf"}
                ],
            },
            {
                "step_id": "step_2",
                "tool": "file_read",
                "success": True,
                "result": {
                    "filename": "Pump Instability Phenomena Generated by Fluid Forces.pdf",
                    "content": (
                        "Section 3: Fluid Force Excitation and Rotor Whirl.\n"
                        "Interaction between rotor and fluid creates cross-coupled dynamic stiffness.\n"
                        "Section 4: Acoustic resonance in discharge piping amplifies vibration pulsations."
                    ),
                },
            },
        ]

        # Call without an active LLM provider to test the deterministic evidence-grounded fallback
        mock_provider = AsyncMock()
        mock_provider.chat.side_effect = Exception("LLM offline")

        synth_result = await engine._synthesize_tabular_data(
            user_request="Create a DOCX technical report with a table of cause, source document, and supporting finding",
            filename="Pump_Instability_Report.docx",
            step_description="Generate DOCX report with table",
            target_headers=["Cause", "Source Document", "Supporting Finding"],
            executed_step_results=executed_step_results,
            sources=[],
            provider=mock_provider,
            model_name="qwen2.5:7b",
        )

        assert synth_result["headers"] == ["Cause", "Source Document", "Supporting Finding"]
        rows = synth_result["rows"]
        assert len(rows) >= 2
        # Check that rows cite the real source document
        for r in rows:
            assert len(r) == 3
            assert r[1] == "Pump Instability Phenomena Generated by Fluid Forces.pdf"
            assert len(r[0]) > 0  # Cause
            assert len(r[2]) > 0  # Supporting Finding

    @pytest.mark.asyncio
    async def test_end_to_end_docx_generation_with_table_and_verification(self, tmp_path: Path):
        """
        Verify the exact end-to-end execution flow of the live user prompt:
        'Create a DOCX technical report using the uploaded PDF documents directly.
        Summarize the main causes of pump instability and vibration, and include a table
        with the cause, source document, and supporting finding. Cite the source documents.
        Do not invent, rename, or substitute filenames.'
        """
        upload_dir = tmp_path / "uploads"
        sandbox_dir = tmp_path / "sandbox"
        upload_dir.mkdir(parents=True, exist_ok=True)
        sandbox_dir.mkdir(parents=True, exist_ok=True)

        # 1. Place the uploaded PDF on disk
        pdf_file = upload_dir / "doc_c966648ec632bcfd_Pump Instability Phenomena Generated by Fluid Forces.pdf"
        pdf_file.write_bytes(_create_minimal_pdf_bytes())

        extracted_pdf_text = (
            "PUMP INSTABILITY PHENOMENA GENERATED BY FLUID FORCES\n\n"
            "Executive Summary:\n"
            "Multi-stage boiler feed and charge pumps suffer from dynamic instability caused by hydrodynamic forces.\n\n"
            "Key Mechanisms & Findings:\n"
            "- Fluid force excitation: Rotor-fluid dynamic interactions produce cross-coupled stiffness forces causing self-excited lateral vibration.\n"
            "- Acoustic resonance: Pressure pulsation frequencies match acoustic natural frequencies of discharge piping, amplifying vibration.\n"
            "- Suction recirculation and cavitation: Low flow rates create inlet vortex shedding and blade starvation.\n"
        )

        with patch("backend.rag.ingest.DocumentParser._parse_pdf", return_value=(extracted_pdf_text, {"page_count": 1})):
            # Step 1: file_list
            fl_tool = create_file_list(upload_dir)
            files = await fl_tool(FileListInput())
            assert len(files) == 1
            filename = files[0]["filename"]
            assert filename == "Pump Instability Phenomena Generated by Fluid Forces.pdf"

            # Step 2: file_read
            fr_tool = create_file_read(upload_dir)
            read_res = await fr_tool(FileReadInput(relative_path=filename))
            assert read_res["filename"] == filename
            assert "Fluid force excitation" in read_res["content"]

            # Step 3: Synthesize table data and content
            engine = AgentEngine.__new__(AgentEngine)
            engine._doc_service = None

            mock_provider = AsyncMock()
            mock_provider.chat.side_effect = Exception("LLM offline")

            executed_results = [
                {"step_id": "step_1", "tool": "file_list", "result": files, "success": True},
                {"step_id": "step_2", "tool": "file_read", "result": read_res, "success": True},
            ]

            table_data = await engine._synthesize_tabular_data(
                user_request="Create a DOCX technical report with a table of cause, source document, and supporting finding",
                filename="Pump_Instability_Report.docx",
                step_description="Generate DOCX report with table",
                target_headers=["Cause", "Source Document", "Supporting Finding"],
                executed_step_results=executed_results,
                sources=[],
                provider=mock_provider,
                model_name="qwen2.5:7b",
            )

            assert table_data["headers"] == ["Cause", "Source Document", "Supporting Finding"]
            assert len(table_data["rows"]) >= 2

            # Step 4: docx_create
            docx_tool = create_docx_create(sandbox_dir)
            docx_res = await docx_tool(DocxCreateInput(
                filename="Pump_Instability_Report.docx",
                title="Pump Instability and Vibration Technical Report",
                content=(
                    "This technical report summarizes the primary causes of pump instability and vibration "
                    "observed in multi-stage centrifugal pumps based on engineering findings."
                ),
                tables=[table_data],
                overwrite=True,
            ))
            assert docx_res["filename"] == "Pump_Instability_Report.docx"
            assert docx_res["size_bytes"] > 0

            # Step 5: artifact_verifier
            verifier = create_artifact_verifier(sandbox_dir)
            verify_res = await verifier(ArtifactVerifierInput(
                relative_path="Pump_Instability_Report.docx",
                expected_columns=["Cause", "Source Document", "Supporting Finding"],
                expected_content=["Fluid force excitation", "Pump Instability Phenomena Generated by Fluid Forces.pdf"],
                min_row_count=1,
            ))

            assert verify_res["verified"] is True
            assert verify_res["status"] == "PASSED_VERIFICATION"
            assert verify_res["table_data_row_count"] >= 2
            assert all(c in verify_res["detected_headers"] for c in ["Cause", "Source Document", "Supporting Finding"])

            # Step 6: Verify file OOXML structure on disk
            import docx
            saved_doc = docx.Document(sandbox_dir / "Pump_Instability_Report.docx")
            assert len(saved_doc.paragraphs) >= 2
            assert len(saved_doc.tables) == 1
            tbl = saved_doc.tables[0]
            # Must have at least 1 header + 2 data rows
            assert len(tbl.rows) >= 3
            headers = [c.text.strip() for c in tbl.rows[0].cells]
            assert headers == ["Cause", "Source Document", "Supporting Finding"]
            for row in tbl.rows[1:]:
                row_texts = [c.text.strip() for c in row.cells]
                assert len(row_texts) == 3
                assert len(row_texts[0]) > 0  # Cause populated
                assert row_texts[1] == "Pump Instability Phenomena Generated by Fluid Forces.pdf"  # Source doc populated
                assert len(row_texts[2]) > 0  # Supporting finding populated
