/**
 * frontend/src/components/artifacts/ArtifactViewer.tsx
 * -----------------------------------------------------
 * Generated Artifacts, Spreadsheets & Compliance Reports Explorer.
 *
 * Features:
 * - List generated reports in data/sandbox/
 * - Format badges (XLSX, CSV, MD, TXT)
 * - Cryptographic SHA-256 hash inspection
 * - One-click download button
 */

import React, { useState, useEffect } from 'react';
import {
  FileSpreadsheet,
  FileText,
  Download,
  RefreshCw,
  CheckCircle2,
  Shield,
  Clock,
  HardDrive,
  FileCode,
} from 'lucide-react';
import { useWorkbench } from '../../context/WorkbenchContext';

interface ArtifactItem {
  filename: string;
  path: string;
  size_bytes: number;
  modified_at: number;
  format: string;
  mime_type: string;
  sha256_hash: string;
}

export const ArtifactViewer: React.FC = () => {
  const [artifacts, setArtifacts] = useState<ArtifactItem[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [lastRefreshed, setLastRefreshed] = useState<string>('');

  const { addToast } = useWorkbench();

  const loadArtifacts = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/artifacts');
      if (res.ok) {
        const data = await res.json();
        setArtifacts(data.artifacts || []);
        setLastRefreshed(new Date().toLocaleTimeString());
      }
    } catch (err: any) {
      addToast('error', `Failed to load artifacts: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadArtifacts();
    const interval = setInterval(loadArtifacts, 10000);
    return () => clearInterval(interval);
  }, []);

  const getFormatIcon = (format: string) => {
    switch (format.toLowerCase()) {
      case 'xlsx':
      case 'xls':
        return <FileSpreadsheet className="w-5 h-5 text-emerald-400" />;
      case 'csv':
        return <FileSpreadsheet className="w-5 h-5 text-blue-400" />;
      case 'md':
      case 'txt':
        return <FileText className="w-5 h-5 text-purple-400" />;
      default:
        return <FileCode className="w-5 h-5 text-slate-400" />;
    }
  };

  const formatSize = (bytes: number) => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
    return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-y-auto bg-[#090d16] text-slate-100 p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-white flex items-center gap-2">
            <FileSpreadsheet className="w-5 h-5 text-emerald-400" />
            Generated Artifacts &amp; Reports
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Structured spreadsheets, compliance audits, and incident logs generated by agent workflows in data/sandbox/.
          </p>
        </div>

        <div className="flex items-center gap-3">
          {lastRefreshed && (
            <span className="text-[11px] font-mono text-slate-500">Updated: {lastRefreshed}</span>
          )}
          <button
            onClick={loadArtifacts}
            disabled={loading}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-700 bg-slate-900 hover:bg-slate-800 text-xs font-mono text-slate-300 transition-colors disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin text-emerald-400' : ''}`} />
            <span>Refresh</span>
          </button>
        </div>
      </div>

      {loading && artifacts.length === 0 ? (
        <div className="flex-1 flex items-center justify-center text-slate-400 text-xs font-mono gap-2 py-16">
          <RefreshCw className="w-4 h-4 animate-spin text-emerald-400" />
          <span>Scanning sandbox output directory...</span>
        </div>
      ) : artifacts.length === 0 ? (
        <div className="bg-[#0d1424]/40 border border-dashed border-slate-800 rounded-xl p-12 text-center space-y-3">
          <HardDrive className="w-8 h-8 text-slate-600 mx-auto" />
          <h3 className="text-sm font-semibold text-slate-300">No Generated Artifacts Yet</h3>
          <p className="text-xs text-slate-500 max-w-md mx-auto">
            Execute an industrial compliance scenario or ask the agent to create a report spreadsheet to see generated artifacts here.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-3">
          {artifacts.map((art) => (
            <div
              key={art.filename}
              className="bg-[#0d1424]/70 border border-slate-800 rounded-xl p-4 flex items-center justify-between hover:border-slate-700 transition"
            >
              <div className="flex items-center gap-3.5 min-w-0">
                <div className="w-10 h-10 rounded-lg bg-slate-900 border border-slate-800 flex items-center justify-center shrink-0">
                  {getFormatIcon(art.format)}
                </div>

                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold text-sm text-slate-200 truncate">{art.filename}</h3>
                    <span className="text-[10px] uppercase font-mono px-1.5 py-0.5 rounded bg-slate-800 text-slate-400 border border-slate-700">
                      {art.format}
                    </span>
                  </div>

                  <div className="flex items-center gap-4 text-[11px] font-mono text-slate-400 mt-1">
                    <span>Size: {formatSize(art.size_bytes)}</span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <Clock className="w-3 h-3 text-slate-500" />
                      {new Date(art.modified_at * 1000).toLocaleString()}
                    </span>
                    <span>•</span>
                    <span className="flex items-center gap-1" title={art.sha256_hash}>
                      <Shield className="w-3 h-3 text-emerald-400" />
                      SHA: {art.sha256_hash.substring(0, 12)}...
                    </span>
                  </div>
                </div>
              </div>

              <div className="flex items-center gap-2 shrink-0 ml-4">
                <a
                  href={`/api/artifacts/${encodeURIComponent(art.filename)}`}
                  download={art.filename}
                  className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download</span>
                </a>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
